install ansible
install asdf
install aws-okta
install awscli
install bat
install ctags
install exa
install fzf
install gh
install go
install grep
install gti
install htop
install int128/kubelogin/kubelogin
install jid
install jq
install k9s
install kind
install krew
install kubectx
install macvim
install nvm
install packer
install pyenv-virtualenv
install rbenv
install reattach-to-user-namespace
install ripgrep
install speedtest-cli
install telnet
install tfenv
install the_silver_searcher
install tmux
install velero
install watch
install wget
install wimlib
install yarn
